- id: check-invalid-domains
  entry: check-invalid-domains
  name: hulks.check_invalid_domains
  language: python
  types: [text]

- id: check-filename
  entry: check-filename
  name: hulks.check_filename
  language: python

- id: check-django-migrations-filename
  entry: check-django-migrations-filename
  name: hulks.check_django_migrations_filename
  language: python

- id: check-logger
  entry: check-logger
  name: hulks.check_logger
  language:  python
  types: [python]

- id: check-mutable-defaults
  entry: check-mutable-defaults
  name: hulks.check_mutable_defaults
  language: python
  types: [python]
