[envs.default]
dependencies = ["pre-commit", "pytest", "pytest-cov", "pytest-deadfixtures"]

[envs.default.env-vars]
SKIP = "no-commit-to-branch"

[envs.default.scripts]
lint = "pre-commit run -a -v"
test = "pytest -x"
check-dead-fixtures = "pytest --dead-fixtures"

[[envs.test.matrix]]
python = ["3.8", "3.9", "3.10", "3.11"]
