from unittest import mock

import pytest

from hulks.check_default_commentary_django_migration import DjangoMigrationCommentary


@pytest.fixture
def hook():
    return DjangoMigrationCommentary()


def test_invalid_migrations_comment_validate(capsys, hook):
    hook.lines_iterator = mock.Mock(return_value=[(1, "# Generated by Django 6.1.9 on 2001-03-22 26:79")])
    result = hook.validate("0002_carrier_active.py")

    output, _ = capsys.readouterr()
    hook.lines_iterator.assert_called_once_with("0002_carrier_active.py")
    assert output.startswith("0002_carrier_active.py")
    assert "line=1" in output
    assert "column=3" in output
    assert result is False


def test_invalid_migrations_comment_validate_unmatch(capsys, hook):
    hook.lines_iterator = mock.Mock(return_value=[(1, "# Generated by Dev")])
    result = hook.validate("0002_carrier_active.py")
    output, _ = capsys.readouterr()
    hook.lines_iterator.assert_called_once_with("0002_carrier_active.py")
    assert output == ""
    assert result is True
