import sys
from typing import Any, Dict, Final, NoReturn, Optional, Sequence

from hulks.base import BaseHook


class DjangoMigrationCommentary(BaseHook):
    DEFAULT_MSG: Final[str] = "Generated by Django"

    def validate(self, filename: str, **options: Dict[str, Any]) -> bool:
        for i, line in self.lines_iterator(filename):
            if self.DEFAULT_MSG in line:
                print(
                    '{}: found "{}" line={}, column={}'.format(
                        filename, self.DEFAULT_MSG, i, line.index(self.DEFAULT_MSG) + 1
                    )
                )
                return False
        return True


def main(args: Optional[Sequence[str]] = None) -> NoReturn:
    """Checks if django migrations files has default commentary"""
    hook = DjangoMigrationCommentary()
    sys.exit(hook.handle(args))


if __name__ == "__main__":
    main(sys.argv[1:])
